**1.** **Our First NumPy Array**

In [2]:
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

np_baseball = np.array(baseball)

print(type(np_baseball))

print(np_baseball)

<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]


**2.** **Baseball players' height**

In [3]:
height_in = [72, 74, 69, 71, 68, 77, 70, 74]

np_height_in = np.array(height_in)

print("Heights in inches:", np_height_in)

np_height_m = np_height_in * 0.0254

print("Heights in meters:", np_height_m)

Heights in inches: [72 74 69 71 68 77 70 74]
Heights in meters: [1.8288 1.8796 1.7526 1.8034 1.7272 1.9558 1.778  1.8796]


**3.** **Baseball player's BMI**

In [6]:
weight_lb = [180, 215, 210, 195, 170, 160, 200, 190]

np_weight_lb = np.array(weight_lb)

np_weight_kg = np_weight_lb * 0.453592

bmi = np_weight_kg / (np_height_m ** 2) # np_height_m is defined in the above cell 

print("BMI values:", bmi)

BMI values: [24.41211827 27.60406069 31.01123531 27.19667848 25.84812523 18.97302091
 28.69669413 24.39428619]


**4.** **Lightweight baseball players**

In [9]:
light = bmi < 21

print("Boolean array:", light)

bmi_below_21 = bmi[light]
print("BMIs of players with BMI below 21:", bmi_below_21)

Boolean array: [False False False False False  True False False]
BMIs of players with BMI below 21: [18.97302091]


In [10]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [11]:
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

**5.** **Blend it all together**

In [12]:
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]


np_positions=np.array(positions)
np_heights=np.array(heights)


gk_heights = np_heights[np_positions == 'GK']

other_heights=np_heights[np_positions!='GK']

print("Median height of goalkeepers: " + str(np.median(gk_heights)))

print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 191.0
Median height of other players: 184.0
